# Opacidad y layout
background_opacity          0.75
cursor_trail                1
window_padding_width        25

# Fuente
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0
confirm_os_window_close 0
scrollbar never

# Colores de pywal (se actualizan con el wallpaper)
include ~/.cache/wal/colors-kitty.conf

allow_remote_control yes
listen_on unix:/tmp/kitty
