# Opacidad y layout
background_opacity          0.75                
window_padding_width        25

# Fuente
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0
confirm_os_window_close 0
scrollbar never
allow_remote_control yes
listen_on unix:/tmp/kitty

include ~/.cache/wal/colors-kitty.conf
allow_remote_control yes
listen_on unix:/tmp/kitty
