font_family MartianMono Nerd Font Mono
font_size 11.0

window_padding_width 14
window_padding_height 12

background_opacity 0.65
hide_window_decorations yes

cursor_shape block
cursor_blink_interval 0

copy_on_select clipboard
paste_actions quote-urls-at-prompt

background #0a0a0a
foreground #e6e6e6
cursor #ffffff
selection_background #1a1a1a
selection_foreground #ffffff

color0 #2e231b
color1 #c0442b
color2 #8a9a5b
color3 #d89a5b
color4 #6f8da0
color5 #b06a78
color6 #7fa89a
color7 #e6d6cb
color8 #594636
color9 #e0563b
color10 #a8b56e
color11 #f0b85e
color12 #8fa9bb
color13 #d08a96
color14 #9fc3b4
color15 #fff6f0

startup_session none
