-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 5.0,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(ffffffff)"},
                angle = 45,
            },
        },
    },
})

-- Bezier curves
hl.curve("almostLinear", { type = "bezier", points = { {0.5, 0.5}, {0.75, 1.0} } })
hl.curve("easeOutQuint", { type = "bezier", points = { {0.23, 1.0}, {0.32, 1.0} } })
hl.curve("gentle", { type = "bezier", points = { {0.4, 0.1}, {0.2, 1.0} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 5.0,
    bezier = "default",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 5.0,
    bezier = "gentle",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 5.0,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5.0,
    bezier = "quick",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.0,
    bezier = "almostLinear",
    style = "fade",
})
