-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    cursor = {
        hide_on_key_press = false,
        hide_on_touch = true,
        inactive_timeout = 5.0,
    },
    dwindle = {
        preserve_split = false,
        smart_split = false,
    },
    general = {
        allow_tearing = false,
        col = {
            active_border = "0xffb6b3af",
            inactive_border = "0xff2e2e2e",
        },
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.02Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
