-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        inactive_timeout = 5.0,
    },
    dwindle = {
        default_split_ratio = 1.0,
        smart_split = false,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(9ad4a1ff)", "rgba(dfe4dcff)"},
                angle = 45,
            },
        },
    },
    input = {
        kb_layout = "us,es",
        kb_options = "grp:lalt_lshift_toggle",
    },
})

-- Bezier curves
hl.curve("ease", { type = "bezier", points = { {0.25, 0.1}, {0.25, 1.0} } })
hl.curve("gentle", { type = "bezier", points = { {0.4, 0.1}, {0.2, 1.0} } })
hl.curve("smooth", { type = "bezier", points = { {0.22, 0.9}, {0.25, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 4.5,
    bezier = "smooth",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.5,
    bezier = "ease",
    style = "slide",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5.5,
    bezier = "gentle",
    style = "slide",
})
